-- 為 Role 表添加主鍵約束

-- 添加 RoleID 主鍵約束
ALTER TABLE Role 
ADD CONSTRAINT PK_Role PRIMARY KEY (RoleID);

-- 檢查主鍵是否添加成功
SELECT 
    CONSTRAINT_NAME, 
    CONSTRAINT_TYPE 
FROM INFORMATION_SCHEMA.TABLE_CONSTRAINTS 
WHERE TABLE_NAME = 'Role' AND CONSTRAINT_TYPE = 'PRIMARY KEY';

